### ISSUE TITLE
Is it possible to start WinXP or Win10 in docker?

### ISSUE THREAD

**Issue by zhangsean** [hectorm/docker-qemu-win2000#2]
Win2000 is too old to fit the modern app.

**Comment by emengweb** [comment]
if could i recommend Win7

**Comment by hectorm** [comment]
It's possible to use this same approach to build an image for any Windows version. But I cannot provide pre-built images of anything newer than Windows 2000 because it will most likely receive a DMCA.

I think it's better if you just manually setup your own VM.

**Comment by sojab0on** [comment]
Simple approach is use this one extract a win xp pro install cd you have to the share using scp/ftp or direct copy depends on where you run the docker. 

then install xp pro and follow the upgrade path to windows 7 pro. 

Dont know if win10 will play nice the qemu/kvm CPU is 32bit so you will need a win10 pro 32bit installer to upgrade to win10 if you wnat. keep in mind that the docker is not fast or responsive with XP i tried even win 7 is slow. 

if you want RDP to function you will need to pro or enterprise versions of windows 10 and 7 otherwise there is no RDP server in the os

**Comment by emengweb** [comment]
all done with it, use dd packet win7ent as the disk file, everything is good :)

**Comment by zhangsean** [comment]
> all done with it, use dd packet win7ent as the disk file, everything is good :)

Would you like to share your setup steps, I'm very interesting in it.

**Comment by sojab0on** [comment]
gues he setup a que/kvm with windows 10 installed 
ran an dd command form al live cd to iamge it 
booted this docker image and trough the shell docker -exec command or trough portainer ran dd command to puthisdd image over the current drive iamge.

**Comment by emengweb** [comment]
> > all done with it, use dd packet win7ent as the disk file, everything is good :)
> 
> Would you like to share your setup steps, I'm very interesting in it.

Sure thing, here: https://github.com/emengweb/emu-windows

chinese version https://d.02es.com/qemu.html

**Comment by emengweb** [comment]
> > all done with it, use dd packet win7ent as the disk file, everything is good :)
> 
> Would you like to share your setup steps, I'm very interesting in it.

Sure thing, here: https://github.com/emengweb/emu-windows

chinese version https://d.02es.com/qemu.html
